services:
  db:
    image: postgres:16
    container_name: ai4juris_db
    restart: always
    environment:
      POSTGRES_DB: ai4jurisdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "11111:5432" # porta externa para o Postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: ai4juris_redis
    restart: always
    ports:
      - "6379:6379"

  web:
    build:
      context: ./backend
    container_name: ai4juris_backend
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    environment:
      DB_NAME: ai4jurisdb
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_HOST: db
      DB_PORT: 5432
      IA_API_URL: ${IA_API_URL:-http://host.docker.internal:8000}
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      DEBUG: "True"
      B2_KEY_ID: "003166250af27550000000001"
      B2_APPLICATION_KEY: "K003Qra5rY2vZjoAEu//lih+vfGQHqg"
      B2_BUCKET_NAME: "ai4juris-v1"
      B2_ENDPOINT_URL: "https://s3.eu-central-003.backblazeb2.com"
      B2_REGION_NAME: "eu-central-003"
    ports:
      - "7777:8000" # porta externa para o backend
    depends_on:
      - db
      - redis

  worker:
    build:
      context: ./backend
    container_name: ai4juris_worker
    command: celery -A config worker -l info
    environment:
      DB_NAME: ai4jurisdb
      DB_USER: admin
      DB_PASSWORD: admin123
      IA_API_TIMEOUT_SEC: "1000"
      DB_HOST: db
      DB_PORT: 5432
      IA_API_URL: ${IA_API_URL:-http://host.docker.internal:8000}
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      DEBUG: "True"
      B2_KEY_ID: "003166250af27550000000001"
      B2_APPLICATION_KEY: "K003Qra5rY2vZjoAEu//lih+vfGQHqg"
      B2_BUCKET_NAME: "ai4juris-v1"
      B2_ENDPOINT_URL: "https://s3.eu-central-003.backblazeb2.com"
      B2_REGION_NAME: "eu-central-003"
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./frontend
      args:
        VITE_BASE: /
        VITE_API_URL: http://localhost:7777
    container_name: ai4juris_frontend
    depends_on:
      - web
    ports:
      - "3333:4173" # porta externa para o frontend

volumes:
  pgdata:
