services:
  db:
    image: postgres:16
    container_name: ai4juris_db
    restart: always
    environment:
      POSTGRES_DB: ai4jurisdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "11111:5432" # porta externa para o Postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: ./backend
    container_name: ai4juris_backend
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    environment:
      DB_NAME: ai4jurisdb
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "7777:8000" # porta externa para o backend
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      args:
        VITE_BASE: /
        VITE_API_URL: http://localhost:7777
    container_name: ai4juris_frontend
    depends_on:
      - web
    ports:
      - "3333:4173" # porta externa para o frontend

volumes:
  pgdata: